import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Snake',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen flex flex-col`}>
        <nav className="m-2">
          <ul className="flex gap-4">
            <li>
              <a href="react">React</a>
            </li>
            <li>
              <a href="react-mobx">React + MobX</a>
            </li>
          </ul>
        </nav>

        {children}
      </body>
    </html>
  );
}
